# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

  use_frameworks!

  # Pods for RxSwift auth flow
  target 'RxSwift auth flow' do
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Moya/RxSwift', '~> 15.0'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'Authenticator Tests' do
    pod 'RxBlocking', '6.5.0'
    pod 'Moya/RxSwift', '~> 15.0'
    pod 'RxTest', '6.5.0'
end
